### ISSUE TITLE
Ahk2Exe.exe is corrupt or doesn't work

### ISSUE THREAD

**Issue by Rainnie-oo7** [AutoHotkey/Ahk2Exe#105]
I downloaded it, re-installed it, but it comes the same error: Cannot compile, compiler won't started: """
Error: Failed attempt to launch program or document:
Action: <C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe>
Params: <>

Specifically: Der Vorgang konnte nicht erfolgreich abgeschlossen werden, da die Datei einen Vi…

	112: Else
	112: If FileExist(ROOT_DIR '\Compiler\Ahk2Exe.exe')
▶	113: Run('"' ROOT_DIR '\Compiler\Ahk2Exe.exe"')
	114: Else
	115: Run(Format('"{1}" /script "{2}\install-ahk2exe.ahk"', A_AhkPath, A_ScriptDir))

"""

**Comment by TAC109** [comment]
This looks like an anti-virus message, and is a false positive from Microsoft. Ahk2Exe has not been changed since 17 May 2024 and you can check the hash against that published in the release notes. In addition, Ahk2Exe (and AutoHotkey) are completely open source and can be checked for problems if necessary.

In the meantime, I recommend that you add an exclusion to Windows Security (or your anti-virus program) for Ahk2Exe.

Cheers
