### ISSUE TITLE
Ahk2Exe v1.1.37.02a0 reported as malware by Windows Defender

### ISSUE THREAD

**Issue by makedir** [AutoHotkey/Ahk2Exe#106]
https://www.virustotal.com/gui/file/05bba28c3820cd8ee65b22f6ebdac11708f2e79d17f2e8632b6fb229dde5e23a/detection

![image](https://github.com/user-attachments/assets/559240a3-e76a-4827-af73-6ce219a1bd8f)

Algorithm : SHA256
Hash      : 05BBA28C3820CD8EE65B22F6EBDAC11708F2E79D17F2E8632B6FB229DDE5E23A
Path      : C:\Program Files\AutoHotkey\Compiler\Ahk2Exe.exe

**Comment by TAC109** [comment]
This is a false positive from Microsoft. Ahk2Exe has not been changed since 17 May 2024 and you can check the hash against that published in the release notes. In addition, Ahk2Exe (and AutoHotkey) are completely open source and can be checked for problems if necessary.

In the meantime, I recommend that you add an exclusion to Windows Security (or your anti-virus program) for Ahk2Exe.

Cheers
