### ISSUE TITLE
Error: #include Lib  file can not be opened

### ISSUE THREAD

**Issue by tdalon** [AutoHotkey/Ahk2Exe#64]
The AHK main file runs properly (under a directory named 'ahk')
If includes a Lib in A_ScriptDir/Lib/ConNext.ahk with : #Include <ConNext>
This ConNext Lib files includes another file in the same Lib directory via #include Encrypt.ahk
When I compile it, it gives this error looking for the Lib Encrypt.ahk not in the A_ScriptDir/Lib directory but in A_ScriptDir in my case: file .../ahk/Encrypt.ahk can not be opened

**Comment by joedf** [comment]
So you mean with a folder structure like so?
```
\---project
    |   Main_script.ahk
    |
    +---ahk
    |       Encrypt.ahk
    |
    \---Lib
            ConNext.ahk
```

**Comment by tdalon** [comment]
The main script is under ahk and Encrypt is under Lib
ahk: MainScript #include <ConNext>
Lib: ConNext: include Encrypt.ahk and Encrypt.ahk

I could get ahk2exe runs by replacing #include Encrypt.ahk by #include <Encrypt>

(thanks for the quick reply)

**Comment by TAC109** [comment]
> The AHK main file runs properly (under a directory named 'ahk')
> If includes a Lib in A_ScriptDir/Lib/ConNext.ahk with : #Include 
> This ConNext Lib files includes another file in the same Lib directory via #include Encrypt.ahk
> When I compile it, it gives this error looking for the Lib Encrypt.ahk not in the A_ScriptDir/Lib directory but in A_ScriptDir in my case: file .../ahk/Encrypt.ahk can not be opened

It is not clear from your description the precise error you are getting. Could you create some demo scripts which show the problem? Also show the directory layout you are using for the demo, as asked for by @joedf 

Cheers

**Comment by tdalon** [comment]
> 
> Also, are you using the Beta 9 version of Ahk2Exe?
> Does the official version of Ahk2Exe distributed with AutoHotkey work ok?
> 
> Cheers

I have AHK Version 1.1.31.01

**Comment by TAC109** [comment]
Thanks. Does your script run correctly without compiling?

According to the #Include documentation, if a directory is not specified then the included file is looked for in the original script file's directory. See quote below:

"File: The name of the file to be included, which is assumed to be in the startup/working directory if an absolute path is not specified (except for Ahk2Exe, which assumes the file is in the script's own directory). Note: SetWorkingDir has no effect on #Include because #Include is processed before the script begins executing."

Cheers

**Comment by TAC109** [comment]
@tdalon 
Has your issue been resolved?

**Comment by TAC109** [comment]
No further input from @tdalon, therefore closed.
