### ISSUE TITLE
Error: The selected base file does not exist (C1)

### ISSUE THREAD

**Issue by GameMashYT** [AutoHotkey/Ahk2Exe#85]
Specifically C:\xxxxxxx\xxxxxx\downloads\ahk2exe-master\AutoHotkeySC.bin
When I drag ahk2exe.ahk in, it doesn't convert without displaying this message. 
Any help?

**Comment by TAC109** [comment]
I take it that you are trying to compile Ahk2Exe from the source code, rather than just using the released beta 9 Ahk2Exe.exe?

In order to compile Ahk2Exe correctly you need to supply an appropriate Base file from an AutoHotkey download, in order for this to succeed. The beta 9 release was made using AutoHotkeyU32.exe version 1.1.34.00 from [here](https://www.autohotkey.com/boards/viewtopic.php?f=24&t=90438). If you wish to use an earlier release of AutoHotkey you will be restricted to using  a *.bin file as the Base file, and an installed version of AutoHotkey will be accessed as well.

Cheers

**Comment by TAC109** [comment]
I’ve updated the `Readme.md` file to include the Base file requirement.
