### ISSUE TITLE
Why are compiled script's executable files importing network libraries?

### ISSUE THREAD

**Issue by diegocr** [AutoHotkey/Ahk2Exe#97]
Hi there,

Those libraries are for example `WSOCK32.dll` and/or `WININET.dll`

Sorry for being obviously paranoid here, but i do find it strange... the script i am compiling is just creating a keyboard and mouse hook.

Might be just me, but i think something is wrong there, for example:

https://www.virustotal.com/gui/file/1d58c8722329f70984e11829bb63d6dc45de7eb468ec9cea5386e4af13becf6b/details

as can be seen there, it was (falsely?) flagged by 28 engines (not only by importing those libs i reckon, tho)

Although, would like to mention i did re-compiled it with the just released 1.37 version and got it flagged 11 times only, which i am pleased with, lol.

https://www.virustotal.com/gui/file/44a568e979a147934b8ffcf05dfb28d51fe3dca95d7907982323d90292aa9d97/details

So... just wondering :)

Thanks!

**Comment by TAC109** [comment]
Any references to network libraries will be coming from the AutoHotkey executable used as the base file in the compilation. 

When a script is compiled the user's script is simply bundled with the version of AutoHotkey specified as the base file, so that when the compiled executable is run, the embedded copy of AutoHotkey interprets the embedded script. This is similar to the way a free standing script is interpreted.

You should note that Ahk2Exe is open source as is AutoHotkey itself. Both can be inspected for problems if required.

If you have any further queries on this subject they would be better addressed to the AutoHotkey forums as any similar antivirus problems would relate to AutoHotkey itself.

Also note that it is unusual for any executable to be given a completely clean report by VirusTotal. This may be because some antivirus companies have a vested interest in selling their paid products vs their free offering.

Cheers

**Comment by diegocr** [comment]
Thanks for the details.

On this case i did used `ANSI 32-bit.bin` to compile it (i don't need 64-bit here nor Unicode, and it does produces smaller executable files)

This base-file alone is detected by 5 engines:

https://www.virustotal.com/gui/file/5eaf64dbf259eb6d8ebe03d461e06d924fe1ad33edc3d408ed83f98a27eb3c73/details

I think it will be nice for your product and an exercise of transparency also shipping bare-minimum base-files, without things such as importing those network libraries and the like when they are not really needed, actually it doesn't looks like it's just referencing the libs and then don't using them, because according to the VT report above the exe file/program is calling the function [InternetOpenA](https://learn.microsoft.com/en-us/windows/win32/api/wininet/nf-wininet-internetopena) which i dunno the purpose for.

If there is any documentation around on how to compile those base-files, i could even offer providing a PR to compile and ship such kind of bare-minimum crafted alternatives, if you want point me on the right path here and i'll be happy to contribute with that.

> You should note that Ahk2Exe is open source as is AutoHotkey itself. Both can be inspected for problems if required.

Yes, we all know how Open Source does work, but one never knows if a team member may became rogue and included something that is not publicly available...you know.

Even if you do setup Github Actions to compile AutoHotkey/Ahk2Exe for you, it may would look safer on that regard, but there will still be some us that won't fully trust that either.

> Also note that it is unusual for any executable to be given a completely clean report by VirusTotal. 

If you do mean executables compiled by Ahk2Exe, then yeah i do agree... anything installing a keyboard hook will be detected as a keylogger. If you did mean any kind of executables, then i do respectfully disagree, have around about ~180 portable programs and literally none of them are flagged by VT :)

**Comment by SaifAqqad** [comment]
> I think it will be nice for your product and an exercise of transparency also shipping bare-minimum base-files, without things such as importing those network libraries and the like when they are not really needed, actually it doesn't looks like it's just referencing the libs and then don't using them, because according to the VT report above the exe file/program is calling the function [InternetOpenA](https://learn.microsoft.com/en-us/windows/win32/api/wininet/nf-wininet-internetopena) which i dunno the purpose for.
- Shipping base files without these libraries would break a lot of the built-in functionality in [AutoHotkey](https://www.autohotkey.com/docs/v1/index.htm), And since AutoHotkey is not a compiled language, you can't compile the base files based on what is used inside your script (like trimming, etc)
- I'm pretty sure `InternetOpenA` is used for http requests (i.e. `UrlDownloadToFile`)

> If there is any documentation around on how to compile those base-files
- [documentation](https://github.com/AutoHotkey/AutoHotkey#how-to-compile), just use the self-contained build config

**Comment by diegocr** [comment]
Thanks!

Let me clarify i meant shipping _additional_ base-files, not _replacements_

e.g.

1. `ANSI 32-bit.bin`
2. `ANSI 32-bit min.bin`
3. ...etc

with such `ANSI 32-bit min.bin` being bare-minimum not including network libs and everything else unneeded for those of us who wouldn't need the extra functionality (e.g. beyond setting up a keyboard/mouse hook which we won't need network access for)

**Comment by TAC109** [comment]
This issue relates more to the AutoHotkey product itself, as this is where the base files used by Ahk2Exe are generated. If you want to pursue this further I suggest that you discuss this on the AutoHotkey [GitHub](https://github.com/AutoHotkey/AutoHotkey) site or in the [AutoHotkey forums](https://www.autohotkey.com/boards/).

Cheers
